<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="IN-LP-229" failures="1" tests="3" name="Test" time="10.54" errors="0" timestamp="2023-11-14T11:23:43 IST">
  <testcase classname="testCases.loginPageTC" name="loginTC_05" time="0.529"/>
  <testcase classname="testCases.herokuTestCase" name="Basic_Auth_Checking" time="6.998"/>
  <testcase classname="testCases.herokuTestCase" name="Broken_Image_Checking" time="2.945">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
at pages.herokuApp.brokenImage(herokuApp.java:57)
at testCases.herokuTestCase.Broken_Image_Checking(herokuTestCase.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Broken_Image_Checking -->
  <testcase classname="testCases.loginPageTC" name="loginTC_04" time="0.0">
    <ignored/>
  </testcase> <!-- loginTC_04 -->
  <testcase classname="testCases.loginPageTC" name="loginTC_03" time="0.0">
    <ignored/>
  </testcase> <!-- loginTC_03 -->
  <testcase classname="testCases.loginPageTC" name="loginTC_02" time="0.0">
    <ignored/>
  </testcase> <!-- loginTC_02 -->
  <testcase classname="testCases.loginPageTC" name="loginTC_01" time="0.0">
    <ignored/>
  </testcase> <!-- loginTC_01 -->
</testsuite> <!-- Test -->
