<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="IN-LP-229" failures="1" tests="5" name="Test" time="9.401" errors="0" timestamp="2023-11-14T12:55:14 IST">
  <testcase classname="testCases.loginPageTC" name="loginTC_05" time="0.455"/>
  <testcase classname="testCases.herokuTestCase" name="Basic_Auth_Checking" time="3.832"/>
  <testcase classname="testCases.herokuTestCase" name="Broken_Image_Checking" time="3.569">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
at pages.herokuApp.brokenImage(herokuApp.java:53)
at testCases.herokuTestCase.Broken_Image_Checking(herokuTestCase.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Broken_Image_Checking -->
  <testcase classname="testCases.herokuTestCase" name="checkbox_checking" time="0.986"/>
  <testcase classname="testCases.herokuTestCase" name="contextAlert" time="0.51"/>
  <testcase classname="testCases.loginPageTC" name="loginTC_02" time="0.0">
    <ignored/>
  </testcase> <!-- loginTC_02 -->
  <testcase classname="testCases.loginPageTC" name="loginTC_01" time="0.0">
    <ignored/>
  </testcase> <!-- loginTC_01 -->
  <testcase classname="testCases.loginPageTC" name="loginTC_04" time="0.0">
    <ignored/>
  </testcase> <!-- loginTC_04 -->
  <testcase classname="testCases.loginPageTC" name="loginTC_03" time="0.0">
    <ignored/>
  </testcase> <!-- loginTC_03 -->
</testsuite> <!-- Test -->
