<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="IN-LP-229" failures="1" tests="6" name="Test" time="9.331" errors="0" timestamp="2023-11-21T17:24:10 IST">
  <testcase classname="testCases.loginPageTC" name="loginTC_05" time="0.342"/>
  <testcase classname="testCases.herokuTestCase" name="Basic_Auth_Checking" time="4.508"/>
  <testcase classname="testCases.herokuTestCase" name="Broken_Image_Checking" time="2.869">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
at pages.herokuApp.brokenImage(herokuApp.java:55)
at testCases.herokuTestCase.Broken_Image_Checking(herokuTestCase.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Broken_Image_Checking -->
  <testcase classname="testCases.herokuTestCase" name="checkbox_checking" time="0.383"/>
  <testcase classname="testCases.herokuTestCase" name="contextAlert" time="0.48"/>
  <testcase classname="testCases.herokuTestCase" name="dragAndDrop" time="0.694"/>
  <testcase classname="testCases.loginPageTC" name="loginTC_03" time="0.0">
    <ignored/>
  </testcase> <!-- loginTC_03 -->
  <testcase classname="testCases.loginPageTC" name="loginTC_02" time="0.0">
    <ignored/>
  </testcase> <!-- loginTC_02 -->
  <testcase classname="testCases.loginPageTC" name="loginTC_04" time="0.0">
    <ignored/>
  </testcase> <!-- loginTC_04 -->
  <testcase classname="testCases.loginPageTC" name="loginTC_01" time="0.0">
    <ignored/>
  </testcase> <!-- loginTC_01 -->
</testsuite> <!-- Test -->
